#############################################################################
# Makefile for building: smokey
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Jan 8 21:08:43 2014
# Project:  smokey.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile smokey.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinc -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/ai.cpp \
		src/car.cpp \
		src/drawer.cpp \
		src/engine.cpp \
		src/gobject.cpp \
		src/gui.cpp \
		src/main.cpp \
		src/obstacle.cpp \
		src/player.cpp \
		src/player_car.cpp moc/moc_drawer.cpp \
		moc/moc_gui.cpp
OBJECTS       = obj/ai.o \
		obj/car.o \
		obj/drawer.o \
		obj/engine.o \
		obj/gobject.o \
		obj/gui.o \
		obj/main.o \
		obj/obstacle.o \
		obj/player.o \
		obj/player_car.o \
		obj/moc_drawer.o \
		obj/moc_gui.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		smokey.pro
QMAKE_TARGET  = smokey
DESTDIR       = 
TARGET        = smokey

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: smokey.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile smokey.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile smokey.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/smokey1.0.0 || $(MKDIR) obj/smokey1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/smokey1.0.0/ && $(COPY_FILE) --parents inc/ai.hpp inc/car.hpp inc/drawer.hpp inc/engine.hpp inc/gobject.hpp inc/gui.hpp inc/obstacle.hpp inc/player.hpp inc/player_car.hpp obj/smokey1.0.0/ && $(COPY_FILE) --parents src/ai.cpp src/car.cpp src/drawer.cpp src/engine.cpp src/gobject.cpp src/gui.cpp src/main.cpp src/obstacle.cpp src/player.cpp src/player_car.cpp obj/smokey1.0.0/ && (cd `dirname obj/smokey1.0.0` && $(TAR) smokey1.0.0.tar smokey1.0.0 && $(COMPRESS) smokey1.0.0.tar) && $(MOVE) `dirname obj/smokey1.0.0`/smokey1.0.0.tar.gz . && $(DEL_FILE) -r obj/smokey1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_drawer.cpp moc/moc_gui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_drawer.cpp moc/moc_gui.cpp
moc/moc_drawer.cpp: inc/drawer.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) inc/drawer.hpp -o moc/moc_drawer.cpp

moc/moc_gui.cpp: inc/gui.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) inc/gui.hpp -o moc/moc_gui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/ai.o: src/ai.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ai.o src/ai.cpp

obj/car.o: src/car.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/car.o src/car.cpp

obj/drawer.o: src/drawer.cpp inc/drawer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/drawer.o src/drawer.cpp

obj/engine.o: src/engine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/engine.o src/engine.cpp

obj/gobject.o: src/gobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gobject.o src/gobject.cpp

obj/gui.o: src/gui.cpp inc/gui.hpp \
		inc/drawer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gui.o src/gui.cpp

obj/main.o: src/main.cpp inc/gui.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/obstacle.o: src/obstacle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/obstacle.o src/obstacle.cpp

obj/player.o: src/player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/player.o src/player.cpp

obj/player_car.o: src/player_car.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/player_car.o src/player_car.cpp

obj/moc_drawer.o: moc/moc_drawer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_drawer.o moc/moc_drawer.cpp

obj/moc_gui.o: moc/moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_gui.o moc/moc_gui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

