######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 29 12:47:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . inc src moc obj
INCLUDEPATH += . inc
OBJECTS_DIR = obj
MOC_DIR = moc

# Input
HEADERS += inc/car.hpp inc/drawer.hpp inc/engine.hpp inc/gui.hpp inc/main.hpp
SOURCES += src/car.cpp src/drawer.cpp src/engine.cpp src/gui.cpp src/main.cpp
